/**
 * Master Datasets for Campus Initiative Autocomplete
 */

const RAW_COLLEGES = [
  // GGSIPU (Guru Gobind Singh Indraprastha University) & Affiliated Colleges
  'Guru Gobind Singh Indraprastha University (GGSIPU / IP University)',
  'Maharaja Agrasen Institute of Technology (MAIT), Delhi',
  'Maharaja Surajmal Institute of Technology (MSIT), Delhi',
  'Vivekananda Institute of Professional Studies (VIPS), Delhi',
  'University School of Information, Communication and Technology (USICT), GGSIPU',
  'Bharati Vidyapeeth’s College of Engineering (BVCOE), New Delhi',
  'Bhagwan Parshuram Institute of Technology (BPIT), Delhi',
  'Jagan Institute of Management Studies (JIMS), Rohini',
  'Dr. Akhilesh Das Gupta Institute of Technology & Management (ADGITM), Delhi',
  'Guru Tegh Bahadur Institute of Technology (GTBIT), Delhi',
  'HMR Institute of Technology & Management (HMRITM), Delhi',
  'Delhi Technical Campus (DTC), Greater Noida',
  'Trinity Institute of Professional Studies (TIPS), Dwarka',
  'Fairfield Institute of Management and Technology (FIMT), Delhi',
  'Delhi Metropolitan Education (DME), Noida',
  'Chanderprabhu Jain College of Higher Studies (CPJ), Delhi',
  'Army Institute of Management & Technology (AIMT), Greater Noida',
  'Banarsidas Chandiwala Institute of Hotel Management & Catering Technology',
  'Delhi Institute of Advanced Studies (DIAS), Delhi',
  'Gitarattan International Business School (GIBS), Delhi',
  'Kalka Institute for Research and Advanced Studies (KIRAS), Delhi',
  'Management Education & Research Institute (MERI), Janakpuri',
  'Rukmini Devi Institute of Advanced Studies (RDIAS), Delhi',
  'Sri Guru Tegh Bahadur Institute of Management and Information Technology (SGTBIMIT)',

  // Top Delhi & NCR Universities & Colleges
  'Delhi Technological University (DTU)',
  'Netaji Subhas University of Technology (NSUT)',
  'Indraprastha Institute of Information Technology (IIIT Delhi)',
  'Jamia Millia Islamia (JMI), New Delhi',
  'Jawaharlal Nehru University (JNU), New Delhi',
  'Delhi University (DU) - Main Campus',
  'St. Stephen’s College, Delhi University',
  'Hindu College, Delhi University',
  'Hansraj College, Delhi University',
  'Miranda House, Delhi University',
  'Lady Shri Ram College for Women (LSR), Delhi University',
  'Sri Venkateswara College (Venky), Delhi University',
  'Ramjas College, Delhi University',
  'Kirori Mal College (KMC), Delhi University',
  'Shri Ram College of Commerce (SRCC), Delhi University',
  'Atma Ram Sanatan Dharma College (ARSD), Delhi',
  'Deen Dayal Upadhyaya College (DDUC), Delhi',
  'Gargi College, Delhi University',
  'Maitreyi College, Delhi University',
  'Kamala Nehru College (KNC), Delhi',
  'Shaheed Sukhdev College of Business Studies (SSCBS), Delhi',

  // Top Global & Indian Universities
  'Stanford University',
  'Harvard University',
  'Massachusetts Institute of Technology (MIT)',
  'University of California, Berkeley',
  'University of California, Los Angeles (UCLA)',
  'University of Oxford',
  'University of Cambridge',
  'Columbia University',
  'Yale University',
  'Princeton University',
  'Cornell University',
  'New York University (NYU)',
  'University of Pennsylvania',
  'University of Chicago',
  'Johns Hopkins University',
  'Northwestern University',
  'University of Toronto',
  'Imperial College London',
  'ETH Zurich',
  'University of Michigan',
  'Duke University',
  'Carnegie Mellon University',
  'University of Texas at Austin',
  'University of Washington',
  'University of Melbourne',
  'Indian Institute of Technology (IIT) Bombay',
  'Indian Institute of Technology (IIT) Delhi',
  'Indian Institute of Technology (IIT) Madras',
  'Indian Institute of Technology (IIT) Kharagpur',
  'Indian Institute of Technology (IIT) Kanpur',
  'Indian Institute of Technology (IIT) Roorkee',
  'Indian Institute of Technology (IIT) Guwahati',
  'National Institute of Technology (NIT) Trichy',
  'National Institute of Technology (NIT) Surathkal',
  'BITS Pilani',
  'Christ University, Bengaluru',
  'Loyola College, Chennai',
  'St. Xavier’s College, Mumbai',
  'Fergusson College, Pune',
  'Manipal Academy of Higher Education',
  'VIT University, Vellore',
  'SRM Institute of Science and Technology',
  'Amity University',
  'Ashoka University',
  'National Law School of India University (NLSIU)',
  'All India Institute of Medical Sciences (AIIMS) New Delhi',
  'Christian Medical College (CMC) Vellore'
];

const RAW_COURSES = [
  // Psychology, Mental Health & Social Sciences
  'B.A. (Hons) - Psychology',
  'B.A. - Clinical & Applied Psychology',
  'B.Sc - Applied Psychology',
  'B.Sc - Psychology & Behavioral Sciences',
  'M.A. - Clinical Psychology',
  'M.A. - Counseling Psychology',
  'M.Sc - Clinical Psychology',
  'M.Sc - Neuropsychology',
  'M.Phil - Clinical Psychology',
  'MSW (Master of Social Work)',

  // Engineering & Technology
  'B.Tech - Artificial Intelligence & Machine Learning (AI/ML)',
  'B.Tech - Automobile Engineering',
  'B.Tech - Aerospace Engineering',
  'B.Tech - Biotechnology',
  'B.Tech - Chemical Engineering',
  'B.Tech - Civil Engineering',
  'B.Tech - Computer Science & Engineering (CSE)',
  'B.Tech - Cyber Security',
  'B.Tech - Data Science & Analytics',
  'B.Tech - Electrical & Electronics Engineering (EEE)',
  'B.Tech - Electronics & Communication Engineering (ECE)',
  'B.Tech - Information Technology (IT)',
  'B.Tech - Mechanical Engineering',
  'B.E. (Bachelor of Engineering)',
  'M.Tech - Computer Science',
  'M.Tech - Data Science & AI',
  'M.Tech - Software Engineering',
  'M.Tech - VLSI & Embedded Systems',

  // Computer Applications & IT
  'BCA (Bachelor of Computer Applications)',
  'MCA (Master of Computer Applications)',
  'B.Sc - Computer Science / IT',
  'M.Sc - Computer Science / Data Analytics',

  // Medicine, Pharmacy & Healthcare
  'MBBS (Bachelor of Medicine & Bachelor of Surgery)',
  'BDS (Bachelor of Dental Surgery)',
  'B.Pharm (Bachelor of Pharmacy)',
  'M.Pharm (Master of Pharmacy)',
  'PharmD (Doctor of Pharmacy)',
  'BPT (Bachelor of Physiotherapy)',
  'MPT (Master of Physiotherapy)',
  'BAMS (Ayurvedic Medicine & Surgery)',
  'BHMS (Homeopathic Medicine & Surgery)',
  'B.Sc Nursing',
  'M.Sc Nursing',
  'B.Sc - Medical Lab Technology (BMLT)',
  'MD / MS (Doctor of Medicine / Master of Surgery)',

  // Management & Commerce
  'BBA (Bachelor of Business Administration)',
  'BBA (Financial Investment Analysis)',
  'BBA - Digital Marketing',
  'MBA (Master of Business Administration)',
  'MBA - Human Resource Management (HR)',
  'MBA - Marketing & Finance',
  'B.Com (Bachelor of Commerce)',
  'B.Com (Honours) - Finance & Accounting',
  'M.Com (Master of Commerce)',
  'Chartered Accountancy (CA / ICAI)',
  'Company Secretary (CS / ICSI)',
  'CMA (Cost & Management Accountant)',

  // Science & Life Sciences
  'B.Sc - Mathematics / Statistics',
  'B.Sc - Physics / Chemistry',
  'B.Sc - Biotechnology / Life Sciences',
  'B.Sc - Microbiology / Biochemistry',
  'M.Sc - Biotechnology / Biochemistry',

  // Law, Humanities & Design
  'LL.B (Bachelor of Laws)',
  'BA LL.B (Hons) - Integrated Law',
  'BBA LL.B (Hons) - Integrated Law',
  'LL.M (Master of Laws)',
  'B.A. (Hons) - Economics',
  'B.A. (Hons) - English Literature',
  'B.A. (Hons) - Journalism & Mass Communication (BJMC)',
  'B.A. (Hons) - Political Science',
  'B.Arch (Bachelor of Architecture)',
  'B.Des (Bachelor of Design)',
  'B.Ed (Bachelor of Education)',

  // Doctorate & Advanced
  'Ph.D. / Doctorate (Doctor of Philosophy)',
  'Postdoctoral Research Fellow',
  'Diploma / Advanced Diploma'
];

const RAW_CITIES = [
  'San Francisco, CA',
  'Palo Alto, CA',
  'San Jose, CA',
  'New York, NY',
  'Boston, MA',
  'Cambridge, MA',
  'Chicago, IL',
  'Los Angeles, CA',
  'Seattle, WA',
  'Austin, TX',
  'San Diego, CA',
  'Washington, DC',
  'Philadelphia, PA',
  'Atlanta, GA',
  'Dallas, TX',
  'Houston, TX',
  'Toronto, ON',
  'Vancouver, BC',
  'Montreal, QC',
  'London',
  'Oxford',
  'Cambridge',
  'Manchester',
  'Edinburgh',
  'Berlin',
  'Munich',
  'Paris',
  'Amsterdam',
  'Zurich',
  'Sydney',
  'Melbourne',
  'Brisbane',
  'Singapore',
  'Tokyo',
  'Seoul',
  'Dubai',
  'Mumbai',
  'New Delhi',
  'Bengaluru',
  'Hyderabad',
  'Pune',
  'Chennai',
  'Kolkata',
  'Noida / Greater Noida',
  'Gurugram (Gurgaon)',
  'Faridabad',
  'Ghaziabad',
  'Ahmedabad',
  'Jaipur',
  'Chandigarh',
  'Lucknow',
  'Indore',
  'Kochi'
];

// Always export pre-sorted Alphabetical lists
export const MASTER_COLLEGES = Array.from(new Set(RAW_COLLEGES)).sort((a, b) => a.localeCompare(b));
export const MASTER_COURSES = Array.from(new Set(RAW_COURSES)).sort((a, b) => a.localeCompare(b));
export const MASTER_CITIES = Array.from(new Set(RAW_CITIES)).sort((a, b) => a.localeCompare(b));
